services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:1.5.0
    container_name: outline-prod-1
    env_file: ./docker.env
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - 8080:3000
    volumes:
      - /data/docker/outline/storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: outline-redis-prod-1
    env_file: ./docker.env
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /data/docker/outline/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:18
    container_name: outline-db-prod-1
    env_file: ./docker.env
    restart: unless-stopped
    expose:
      - "5432"
    volumesq:
      - /data/docker/outline/db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
