# Only for Pi-Hole releases >= 6
---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # -- Port mappings are irrelevant when using macvlan
    environment:
      # --> Necessary on systems like Synology or Ugreen
      DNSMASQ_USER: root
      # <--
      TZ: Europe/Berlin
      FTLCONF_webserver_api_password: changeme
    volumes:
      - /volume1/docker/pihole/etc:/etc/pihole
      - /volume1/docker/pihole/dnsmasq:/etc/dnsmasq.d
    cap_add:
      # --> Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # <--
      # --> Required on Synology and Ugreen, otherwise there will be warnings in the logs
      - CAP_SYS_TIME
      # <--
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.200.9
        ipv6_address: fd00:0:0:200::9
networks:
  default:
    name: mvl-200
    external: true
