# Copyright (c) 2024 Navigio UG (haftungsbeschränkt)
# This script is provided 'as-is', without any express or implied warranty. 
# In no event will the authors be held liable for any damages arising from the use of this script.
#
# Permission is granted to anyone to use this script for any purpose, including 
# commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
#
# 1. The origin of this script must not be misrepresented; 
#    you must not claim that you wrote the original script. 
#    If you use this script in a product, an acknowledgment in the product 
#    documentation would be appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be misrepresented as 
#    being the original script.
# 3. This notice may not be removed or altered from any source distribution.

services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '80:80' # default is 3010
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - /volume1/docker/affine/config:/root/.affine/config
      # blob storage
      - /volume1/docker/affine/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      - AFFINE_SERVER_HOST=192.168.210.44
      - AFFINE_SERVER_PORT=80 # default is 3010
      - PUID=1028
      - PGID=100
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=admin@example.com
      - AFFINE_ADMIN_PASSWORD=GEHEIM
    networks:
      default:
        ipv4_address: 192.168.210.44
        ipv6_address: fd00:0:0:210::44
    
  redis:
    image: redis
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - /volume1/docker/affine/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        ipv4_address: 192.168.210.45
        ipv6_address: fd00:0:0:210::45

  postgres:
    image: postgres
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - /volume1/docker/affine/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      default:
        ipv4_address: 192.168.210.46
        ipv6_address: fd00:0:0:210::46

networks:
  default:
    name: mvl-210
    external: true
