version: '3'
services:
  database:
    image: postgis/postgis:15-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - /volume3/docker/directus-demo/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    # If you want to interact with this database outside of Directus,
    # e.g. for monitoring purposes, uncomment the following lines and 
    # adjust the IP address accordingly:
    networks:
       default:
         ipv4_address: 192.168.200.11

  cache:
    image: redis:6
    # If you want to persist Redis data, uncomment the following 2 lines:
    # volumes:
    #   - /volume3/docker/directus-demo/redis-data:/data
    networks:
      default:
        ipv4_address: 192.168.200.12

  directus:
    image: directus/directus:latest
    # Port mapping is not required when using macvlan
    # ports:
    #   - 8055:8055
    volumes:
      - /volume3/docker/directus-demo/uploads:/directus/uploads
      - /volume3/docker/directus-demo/extensions:/directus/extensions
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: 'c2cc12b6-6a5f-41bf-b4d9-5c601f7ae6ad'
      SECRET: '6f02e7d7-3467-4177-a50b-34ea46f186c1'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'GEHEIM'

      # EMAIL_SMTP_HOST:
      # EMAIL_SMTP_PORT:
      # EMAIL_SMTP_USER:
      # EMAIL_SMTP_PASSWORD:
      # EMAIL_SMTP_SECURE: TLS

      EMAIL_SES_CREDENTIALS__ACCESS_KEY_ID: DUD3PPUHAH4BTVK3EEX2COV0
      EMAIL_SES_CREDENTIALS__SECRET_ACCESS_KEY: zjlh02VzD5d3Ppd68lfzyPDkAmKeM3jTtHvm3gRXKjhM
      EMAIL_SES_REGION: US (Montana)

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
    # labels:
    #     - "com.centurylinklabs.watchtower.enable=true"
    networks:
      default:
        ipv4_address: 192.168.200.13

networks:
  default:
    name: mvl-200
    external: true
