services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly-core-demo
    restart: unless-stopped
    volumes:
      - /volume1/docker/firefly/upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly-net
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:18
    hostname: db
    container_name: firefly-db-demo
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly-net
    volumes:
      - /volume1/docker/firefly/db:/var/lib/postgresql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    # Use this URL for inspiration: https://www.random.org/strings/?num=1&len=32&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new
    #
    image: alpine
    restart: unless-stopped
    container_name: firefly-cron-demo
    env_file: .env
    command: ["sh", "-c", "apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\" \
      | crontab - && \
      crond -f -L /dev/stdout"]
    networks:
      - firefly-net
    depends_on:
      - app

networks:
  firefly-net:
    external: true
