services:
  teammapper_db:
    container_name: teammapper-db-demo-1
    image: postgres:15-alpine
    env_file:
      - stack.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    volumes:
      - /volume3/docker/teammapper/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      default:
          ipv4_address: 192.168.200.12
          ipv6_address: fd00:0:0:200::12

  teammapper:
    container_name: teammapper-demo-1
    image: ghcr.io/b310-digital/teammapper:latest
    env_file:
      - stack.env
    environment:
      - MODE=${PROD_MODE:-PROD}
      - BINDING="0.0.0.0"
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_HOST=teammapper_db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_QUERY_TIMEOUT=${POSTGRES_QUERY_TIMEOUT:-100000}
      - POSTGRES_STATEMENT_TIMEOUT=${POSTGRES_STATEMENT_TIMEOUT:-100000}
      - POSTGRES_SSL=false
      - DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS:-30}
    ports:
      - ${APP_PORT:-80}:3000
    depends_on:
      - teammapper_db
    networks:
      default:
          ipv4_address: 192.168.200.13
          ipv6_address: fd00:0:0:200::13

networks:
  default:
    name: mvl-200
    external: true
