http:
    middlewares:
        crowdsec-bouncer:
            forwardauth:
                address: http://bouncer-traefik:8080/api/v1/forwardAuth
                trustForwardHeader: true

    routers:
        to-pihole-1:
            rule: "Host(`pihole-2.navigio.io`)"
            tls:
                certResolver: route53
            service: pihole2

    services:
        pihole2:
            loadBalancer:
                servers:
                - url: http://192.168.200.9
