http:
    routers:
        to-pihole-1:
            rule: "Host(`pihole-1.navigio.io`)"
            tls:
                certResolver: route53
            service: pihole1

    services:
        pihole1:
            loadBalancer:
                servers:
                - url: http://192.168.0.15
