global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  route53:
    acme:
      email: juergen@example.com # change this!
      # For testing un-comment the following line:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # For testing:
      # storage: /etc/traefik/certs/route53-acme-test.json
      # For production: 
      storage: /etc/traefik/certs/route53-acme.json
      dnsChallenge:
        provider: route53
        resolvers:
          - "1.1.1.1:53"
          - "9.9.9.9:53"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true
