services:
  traefik:
    container_name: traefik-demo-1
    image: traefik:3.0.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /volume1/docker/traefik/conf/:/etc/traefik/conf/
      - /volume1/docker/traefik/certs/:/etc/traefik/certs/
      - /volume1/docker/traefik/users/:/etc/traefik/users/
      - /volume1/docker/traefik/logs/:/var/log/traefik
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_HOSTED_ZONE_ID
    restart: unless-stopped
    networks:
      proxy:

networks:
  proxy:
    external: true
