# Example docker-compose file for TimeTagger that uses the published
# Docker image in the default root variant.
# Shows all options settable via the environment.
#
# !! Make sure to apply your own credentials                       !!
# !! You can use e.g. https://timetagger.app/cred to generate them !!
# !! In docker-compose characters '$' should be escaped as '$$'    !!
# !! If you use a .env file, use single quotes instead of escaping !!

version: "3"
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    container_name: timetagger-demo-1
    ports:
      - 7780:80
    volumes:
      - /data/docker/timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=demo:$$2a$$08$$caIL2/UxDP0VAsMqtO/GG.FEK9a9rMRMKrn0r.q5Z4/7CrDj.nQ0i # demo/demo
    networks:
      default:
        ipv4_address: 192.168.210.20
        ipv6_address: fd00:0:0:210::20
networks:
  default:
    name: mvl-210
    external: true
