---
services:
    pairdrop:
        image: "lscr.io/linuxserver/pairdrop:latest"
        container_name: pairdrop-demo-1
        restart: unless-stopped
        environment:
            - PUID=1026 # UID to run the application as
            - PGID=100 # GID to run the application as
            - WS_FALLBACK=false # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
            - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
            - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers.
            - DEBUG_MODE=false # Set to true to debug container and peer connections.
            - TZ=Etc/UTC # Time Zone
        # ports:
        #     - "127.0.0.1:3000:3000" # Web UI
        networks:
            default:
                ipv4_address: 192.168.200.10
                ipv6_address: fd00:0:0:200::10
    
networks:
  default:
    name: mvl-200
    external: true
